# Usa una imagen oficial de Node.js como imagen base
FROM node:20.17-alpine AS dist

# Establece el directorio de trabajo
WORKDIR /react-front

# copiar el archivo package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de la aplicación
COPY . .

# Construye la aplicación para producción
RUN npm run build

# Usa una imagen oficial de Nginx como imagen base para servir la aplicación
FROM nginx AS prod-stage

# Copia los archivos de la aplicación construida
COPY --from=dist /react-front/dist /usr/share/nginx/html
# Copia la configuración de Nginx 
COPY --from=dist /react-front/default.conf /etc/nginx/conf.d/

# Expone el puerto 80
EXPOSE 80

# Inicia Nginx
CMD ["nginx", "-g", "daemon off;"]